# Verified in-scope European A&D IPO / M&A events absent from the original Europe tab.
# tuple: target, target country, hq, acquirer/venue, acquirer country, seller, event, structure, stake,
#        ann, comp, status, val_usd_mn, local, basis, disclosure, tier, domain, description, source
ADD = [
("TKMS AG & Co. KGaA","Germany","Kiel, Germany","Frankfurt Stock Exchange (Prime Standard)","N/A - Listing","thyssenkrupp AG",
 "IPO","Spin-off / technical listing","49% distributed to thyssenkrupp shareholders","2025-08-13","2025-10-20","Completed",
 None,"No primary proceeds; ~EUR 6.8bn market value at debut","Spin-off - no gross proceeds","Not applicable (spin-off)",
 "Core A&D","Naval & Underwater Systems",
 "Submarines, frigates and maritime defence systems. Europe's largest pure-play naval defence listing of the period; order backlog ~EUR 18.6bn at listing.",
 "https://www.tkmsgroup.com/news/article/tkms-lists-on-the-frankfurt-stock-exchange-successful-market-debut-for-maritime-defense-provider"),

("THEON International PLC","Greece","Athens, Greece (Cyprus-incorporated)","Euronext Amsterdam","N/A - IPO",None,
 "IPO","Initial public offering","15.4m shares = 22% of issued capital","2024-01-25","2024-02-07","Completed",
 154*1.08,"EUR 154m gross incl. over-allotment; EUR 700m market cap at EUR 10.00/share","IPO gross proceeds","Disclosed",
 "Core A&D","Defence Electronics & Sensors",
 "Developer and manufacturer of customisable night-vision and thermal imaging systems for defence and security.",
 "https://www.euronext.com/en/about/media/euronext-press-releases/theon-international-plc-lists-euronext-amsterdam"),

("Hispasat","Spain","Madrid, Spain","Indra Group","Spain","Redeia Corporacion",
 "Merger/Acquisition","Majority stake","89.68%","2025-01-31","2025-12-30","Completed",
 725*1.09,"EUR 725m","Equity consideration for 89.68%","Disclosed",
 "Core A&D / Space","Space & Satellite Systems",
 "Spanish satellite operator; the transaction also carries a stake in Hisdesat, Spain's governmental and military satellite operator.",
 "https://www.indragroup.com/en/news/indra-group-reaches-agreement-redeia-purchase-897-hispasat-including-stake-hisdesat"),

("Intelsat","Luxembourg","Luxembourg","SES","Luxembourg",None,
 "Merger/Acquisition","Full Acquisition","100%","2024-04-30","2025-07-17","Completed",
 3100.0,"USD 3.1bn","Enterprise value","Disclosed",
 "Core A&D / Space","Space & Satellite Systems",
 "Geostationary and multi-orbit satellite operator serving government, defence and mobility customers.",
 "https://www.ses.com/press-release/ses-completes-acquisition-intelsat"),

("Preligens (renamed Safran.AI)","France","Paris, France","Safran","France",None,
 "Merger/Acquisition","Full Acquisition","100%","2024-06-24","2024-09-02","Completed",
 220*1.09,"EUR 220m","Enterprise value","Disclosed",
 "Core A&D","Defence Software & Digital Systems",
 "AI analytics for high-resolution satellite imagery, full-motion video and acoustic signals; automatic detection and identification of objects of military interest.",
 "https://www.safran-group.com/pressroom/ai-leader-preligens-joins-safran-2024-09-02"),

("OHB SE","Germany","Bremen, Germany","KKR","United States","Fuchs family (retained majority)",
 "Merger/Acquisition","Voluntary public takeover offer + delisting","Minority stake; Fuchs family retained ~70%","2023-08-08","2023-10-17","Completed",
 1000*1.09,"EUR 44.00 per share; ~EUR 1bn enterprise value","Enterprise value","Disclosed",
 "Core A&D / Space","Space & Satellite Systems",
 "European space systems prime: satellites, launchers and space exploration; subsequently delisted from the Frankfurt Stock Exchange.",
 "https://www.ohb.de/en/investor-relations/ir-news/ir-announcements/management-board-and-supervisory-board-of-ohb-se-recommend-accepting-the-voluntary-public-takeover-offer-by-kkr"),

("Milrem Robotics","Estonia","Tallinn, Estonia","EDGE Group","United Arab Emirates",None,
 "Merger/Acquisition","Majority stake","Majority","2023-02-15","2023-02-15","Completed",
 None,"Not disclosed","n/a","Not disclosed",
 "Core A&D","UAVs & Autonomous Systems",
 "Europe's leading developer of unmanned ground vehicles and robotic warfare systems; the largest foreign investment in Estonia's defence industry.",
 "https://edgegroup.ae/news/edge-acquires-majority-stake-milrem-robotics-europes-leading-developer-robotics-and-autonomous"),

("Spirit AeroSystems Belfast and Prestwick operations","United Kingdom","Belfast, Northern Ireland / Prestwick, Scotland","Airbus","Netherlands","Spirit AeroSystems Holdings",
 "Merger/Acquisition","Carve-out","100% of the European sites","2025-04-28","2025-12-08","Completed",
 None,"Airbus received USD 439m compensation (net payment to Airbus)","Compensation received by acquirer","Disclosed",
 "Core A&D","Aerospace Platforms & Components",
 "A220 wings and mid-fuselage (Belfast) and A320/A350 wing components (Prestwick); ~4,000 employees transferred.",
 "https://www.airbus.com/en/newsroom/press-releases/2025-12-airbus-completes-acquisition-of-spirit-aerosystems-sites"),

("CS Group","France","Le Plessis-Robinson, France","Sopra Steria","France",None,
 "Merger/Acquisition","Majority stake","75.06%","2022-07-27","2023-02-28","Completed",
 None,"EUR 11.50 per share","Offer price per share","Disclosed",
 "Core A&D","Defence Software & Digital Systems",
 "Digital services and critical systems for defence and security, space and energy; ~2,500 employees.",
 "https://www.soprasteria.com/newsroom/press-releases/details/sopra-steria-finalises-its-acquisition-of-a-majority-stake-in-the-share-capital-of-cs-group"),

("MARSS Group (defence business)","Monaco","Monaco / United Kingdom","Electro Optic Systems Holdings","Australia",None,
 "Merger/Acquisition","Asset purchase","Whole defence business","2026-01-13","2026-01-13","Completed",
 36.0,"USD 36m upfront (+ earn-out up to EUR 100m tied to new orders)","Upfront cash consideration","Disclosed",
 "Core A&D","Counter-UAS",
 "Counter-drone command-and-control and integrated effectors. Distinct from, and subsequent to, the interceptor-only asset deal recorded at EUR-145.",
 "https://eos-aus.com/news/acquisition-of-marss-counter-drone-c2-system-provider/"),

("Deimos (Elecnor Deimos)","Spain","Tres Cantos, Spain","Indra Group","Spain","Elecnor",
 "Merger/Acquisition","Full Acquisition","100%","2024-08-07","2024-12-31","Completed",
 None,"Not disclosed in the sheet's source set","n/a","Not disclosed",
 "Core A&D / Space","Space & Satellite Systems",
 "Small-satellite mission specialist: satellite design, ground segment and Earth observation systems.",
 "https://spacenews.com/spanish-defense-contractor-buys-small-satellite-mission-specialist-deimos/"),

("Horstman Group","United Kingdom","Bath, United Kingdom","RENK Group","Germany",None,
 "Merger/Acquisition","Full Acquisition","100%","2024-01-01","2024-01-01","Completed",
 None,"Not disclosed","n/a","Not disclosed",
 "Core A&D","Land Systems & Military Vehicles",
 "Suspension systems for tracked military vehicles. Present in the workbook's own Master_Deals tab (EUR-096) but absent from the Europe tab.",
 "Workbook Master_Deals tab, row EUR-096"),

("INFODAS","Germany","Cologne, Germany","Airbus Defence and Space","Netherlands",None,
 "Merger/Acquisition","Full Acquisition","100%","2024-01-01","2024-01-01","Completed",
 None,"Not disclosed","n/a","Not disclosed",
 "Core A&D","Cyber & Digital Defence",
 "Cross-domain security gateways and IT security for government and defence. Present in the workbook's own Master_Deals tab (EUR-094) but absent from the Europe tab.",
 "Workbook Master_Deals tab, row EUR-094"),

("Inzpire","United Kingdom","Lincoln, United Kingdom","QinetiQ","United Kingdom",None,
 "Merger/Acquisition","Full Acquisition","100%","2024-01-01","2024-01-01","Completed",
 None,"Not disclosed","n/a","Not disclosed",
 "Core A&D","Defence Services & Engineering",
 "Military training, mission support and operational advisory services. Present in the workbook's own Master_Deals tab (EUR-108) but absent from the Europe tab.",
 "Workbook Master_Deals tab, row EUR-108"),
]
