# Field-level corrections to apply. Keys map to the corrected Europe tab schema.
# comp = Completion Date, ann = Announcement Date, val = Deal Value (USD mn), basis = Value Basis,
# disc = Value Disclosure, stat = Deal Status, struct = Deal Structure, stake = Stake Acquired,
# tc = Target Country, ac = Acquirer Country, tgt = Target name, dom = A&D Domain, tier = Inclusion Tier,
# loc = Reported consideration (local), scope = A&D Scope Test
C = {
"EUR-005": dict(struct="Share-based merger", basis="Announced transaction value", loc="USD 3.4bn (all-share combination)",
                note="Share-based combination, not a cash purchase. Derived multiples cleared as meaningless (EV/Revenue 390.68x, Deal Size/EBITDA -4.49x)."),
"EUR-007": dict(ann="2025-07-30", comp="2026-03-18", year=2026, loc="EUR 1.7bn", basis="Enterprise value", disc="Disclosed"),
"EUR-010": dict(tc="Germany", hq="Huerth, Germany", stat="Announced/In Progress", comp=None, ann="2026-04-13",
                loc="USD 1.45bn", basis="Enterprise value", disc="Disclosed", scope="Marginal"),
"EUR-011": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a",
                note="Sheet's USD1,352.60m and synopsis's USD1,055.61m both removed - consideration was never disclosed."),
"EUR-012": dict(comp="2023-08-01", ann="2022-11-01"),
"EUR-014": dict(val=402.5*1.08, loc="EUR 402.5m gross (incl. over-allotment)", basis="IPO gross proceeds", disc="Disclosed",
                postval=1016*1.08, note="Corrected from EUR1.10bn/EUR3.90bn. 50,782,552 shares admitted; market cap ~EUR1.016bn."),
"EUR-015": dict(val=1100.0, loc="USD 1.1bn", basis="Enterprise value", disc="Disclosed", comp="2024-04-02", ann="2023-07-11"),
"EUR-017": dict(val=675*1.088, loc="EUR 675m EV (+ earn-out up to EUR 55m)", basis="Enterprise value, excl. earn-out",
                disc="Disclosed", comp="2024-04-02", ann="2023-12-05"),
"EUR-018": dict(tc="United Kingdom", hq="St Asaph, Wales, United Kingdom", val=710.0,
                loc="USD 710m (Excelitas A&D electronics, incl. a US business)", basis="Purchase price - part non-European",
                disc="Disclosed", note="Price covers UK Qioptiq optics AND a US advanced electronics business; not wholly attributable to Europe."),
"EUR-022": dict(stat="Completed", comp="2026-07-01", ann="2026-02-03", loc="EUR 570m", basis="Enterprise value (cash/debt free)", disc="Disclosed"),
"EUR-024": dict(comp="2023-01-20", loc="EUR 622m (EUR 20.00/share)", basis="Transaction value", disc="Disclosed", val=675.0),
"EUR-025": dict(stat="Completed", comp="2026-07-02", ann="2026-03-03", loc="USD 615m (USD 480m cash + USD 135m shares)", disc="Disclosed"),
"EUR-026": dict(loc="EUR 15.00/share; 33,333,333 shares; ~EUR 500m", basis="IPO gross proceeds (all secondary)",
                note="Synopsis corrected: placement price was EUR15.00/share, not USD1.00."),
"EUR-029": dict(val=550.0, loc="USD 550m cash", basis="Purchase price", disc="Disclosed", comp="2025-04-28"),
"EUR-031": dict(basis="IPO secondary placement - NO proceeds to company", acq=None, ac="N/A - IPO",
                loc="EUR 17.00/share; 20,297,500 shares; ~EUR 345m",
                note="Pure secondary sell-down by STAR Capital; company issued no shares and received no proceeds. Fidelity/Invesco/T. Rowe Price were cornerstone investors, not acquirers."),
"EUR-032": dict(stat="Completed", comp="2026-07-07", ann="2026-04-30", val=46.3,
                loc="USD 46.3m initial consideration (up to USD 54.4m with escrow release)", basis="Initial consideration", disc="Disclosed",
                note="Sheet's USD355m is not supported by the acquirer's own disclosure."),
"EUR-033": dict(comp="2023-09-29", ann="2023-08-11", loc="~CHF 240m for 80.9%", basis="Consideration for 80.9% stake",
                stake="80.9% (tender offer second closing 28-Nov-2023 took the group to 85.0%)", struct="Majority stake + tender offer"),
"EUR-034": dict(scope="Fail", note="GF Casting Solutions AUTOMOTIVE division (~80% e-mobility/chassis)."),
"EUR-036": dict(scope="Fail", tier="Adjacent / Dual-Use", dom="Industrial Services (non-A&D)",
                note="Hydraulic-hose replacement franchise; reclassified out of Core A&D."),
"EUR-037": dict(val=2.47, loc="INR 205.624m", basis="Purchase price", disc="Disclosed", scope="Fail",
                tier="Adjacent / Dual-Use", dom="Water Infrastructure (non-A&D)",
                note="Value corrected from USD254.06m (~100x error). 'Flood defence' is water infrastructure."),
"EUR-038": dict(val=186*1.08, loc="HUF 74.5-82.8bn (EUR 186-207m)", basis="Range - low end shown", stake="75% + 1 vote",
                struct="Majority stake", disc="Disclosed (range)"),
"EUR-039": dict(comp="2024-06-01", ann="2022-06-24", year=2024, val=268.0, loc="~EUR 247m (USD 268m)", disc="Disclosed",
                note="Originally announced Jun-2022 at EUR226m; BLOCKED by Denmark May-2023; cleared 06-May-2024; completed 01-Jun-2024 at a higher price."),
"EUR-041": dict(comp="2024-08-19", ann="2024-03-27", val=200.0, loc="EUR 6.30/share; ~EUR 200m equity value; USD 200m net of cash", disc="Disclosed"),
"EUR-042": dict(disc="Vendor estimate - not independently confirmed"),
"EUR-043": dict(val=200.0, loc="USD 200m cash", disc="Disclosed", comp="2024-12-01"),
"EUR-044": dict(val=None, loc="Not disclosed (~11x EBITDA indicated)", disc="Not disclosed", basis="n/a"),
"EUR-048": dict(comp="2026-04-14", ann="2025-03-10", val=155.3, loc="USD 155.3m", disc="Disclosed"),
"EUR-052": dict(val=147.0, loc="EUR 135m", disc="Disclosed", tgt="Mannesmann Stainless Tubes (renamed DMV)", scope="Marginal"),
"EUR-054": dict(ann="2024-09-30", comp="2025-02-01", year=2025, stake="26.33% (24.67% -> 51.01%)", struct="Stake increase to majority",
                loc="EUR 106.7m (+ earn-out up to EUR 30m)", basis="Consideration for 26.33% stake", disc="Disclosed"),
"EUR-055": dict(disc="Vendor estimate - not independently confirmed", scope="Fail", note="Boring/milling machine tools."),
"EUR-056": dict(comp="2023-06-20", year=2023, loc="EUR 98m", disc="Disclosed", stake=">93% via public tender offer", struct="Public tender offer"),
"EUR-057": dict(scope="Marginal", tier="Adjacent / Dual-Use", dom="Industrial Imaging & Machine Vision",
                loc="EUR 103m (~USD 100m)", disc="Disclosed"),
"EUR-060": dict(val=99.0, loc="GBP 75m enterprise value", disc="Disclosed", scope="Fail", dom="Nuclear Engineering (non-A&D)"),
"EUR-061": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-062": dict(tgt="Harland & Wolff (Belfast, Appledore, Methil, Arnish)", ac="Spain",
                note="Acquirer Navantia UK is the UK subsidiary of Spanish state-owned Navantia. Target renamed from post-administration shell name."),
"EUR-064": dict(val=None, loc="Not disclosed (>20x EBITDA reported)", disc="Not disclosed", basis="n/a",
                struct="Purchase of Albarest Partners and Definvest stakes", stake="Stakes of two shareholders"),
"EUR-065": dict(comp="2024-02-02", tier="Core A&D", note="Reclassified from Adjacent/Dual-Use: heavy-lift military UAV maker acquired by BAE Systems."),
"EUR-070": dict(comp="2025-10-21", ann="2025-04-26", val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a", seller="TKH Group N.V."),
"EUR-071": dict(comp="2025-10-31", ann="2025-08-28", val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-072": dict(val=35*1.08, loc="EUR 35m at closing (+ up to EUR 10m earn-out)", basis="Consideration at closing", disc="Disclosed"),
"EUR-073": dict(loc="EUR 45m", disc="Disclosed", scope="Fail", dom="Foundry / Heavy Industrial Castings (non-A&D)"),
"EUR-075": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a", stat="Completed",
                note="Public sources place completion variously in 2024 and Mar-2025; date retained as reported but flagged."),
"EUR-076": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a", scope="Fail", dom="Welding Robotics (non-A&D)"),
"EUR-078": dict(val=25*1.27, loc="GBP 25m fixed EV (+ earn-out up to GBP 7m)", basis="Fixed enterprise value, excl. earn-out", disc="Disclosed"),
"EUR-079": dict(ann="2023-12-19", comp="2024-03-31", scope="Fail", dom="Dimensional Metrology (non-A&D)",
                loc="~USD 44m", disc="Disclosed"),
"EUR-081": dict(comp="2026-02-25", ann="2025-11-26", dom="Protective Equipment & Soldier Systems"),
"EUR-082": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-083": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a",
                note="Sheet's GBP32m implies 12.8x revenue for a 17-employee, GBP2.5m-revenue business the buyer said would have only a marginal EPS effect. Removed as not credible."),
"EUR-084": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a", tier="Core A&D",
                note="Reclassified: cooled IR camera cores for defence surveillance and counter-UAS."),
"EUR-085": dict(comp="2024-02-14", val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-086": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a", ann="2024-03-01"),
"EUR-087": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-088": dict(comp="2024-05-10", val=32.4*0.735, loc="CAD 32.4m at closing (up to CAD 41m / GBP 24m)",
                basis="Consideration at closing", disc="Disclosed"),
"EUR-091": dict(val=17.1*1.16, loc="EUR 17.1m (~SEK 190m); base EUR 16.4m + earn-out up to EUR 18m",
                basis="Completion consideration", disc="Disclosed"),
"EUR-093": dict(ac="India", note="Sigma Advanced Systems is an Indian group; Sigma Advanced Systems UK Ltd is its UK acquisition vehicle."),
"EUR-096": dict(val=21.9, loc="USD 21.0m net cash + USD 0.9m pension liability", disc="Disclosed", scope="Fail",
                dom="Automotive Steel Laminations (non-A&D)"),
"EUR-098": dict(comp="2024-01-10", val=15.7*1.09, loc="EUR 15.7m initial (+ up to EUR 3m contingent)",
                basis="Initial consideration", disc="Disclosed"),
"EUR-099": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-102": dict(val=12.3*1.28, loc="GBP 12.3m initial cash", basis="Initial consideration", disc="Disclosed"),
"EUR-103": dict(ann="2025-07-15", comp="2025-09-30", val=16.3, loc="GBP 12.2m total (GBP 9.2m upfront)",
                basis="Total consideration", disc="Disclosed", scope="Marginal"),
"EUR-104": dict(stake="30% -> 65%", struct="Stake increase to control", loc="~EUR 16m", disc="Disclosed",
                note="Not a full acquisition. The 65%->100% step is a separate 2026 transaction (see EUR-210)."),
"EUR-111": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-116": dict(val=5.0*1.09, loc="EUR 5.0m initial (max EUR 11.0m incl. up to EUR 6.0m contingent)",
                basis="Initial consideration", disc="Disclosed", scope="Fail", tier="Adjacent / Dual-Use",
                dom="Automotive Test Equipment (non-A&D)"),
"EUR-117": dict(val=4.0, loc="USD 4.0m initial (up to USD 8.4m with contingent consideration)",
                basis="Initial consideration", disc="Disclosed", scope="Fail", tier="Adjacent / Dual-Use",
                dom="High-Visibility Textiles (non-A&D)", note="Coats reports Viz Reflectives in its Apparel segment."),
"EUR-121": dict(comp="2024-10-08", val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a",
                stake="94.09%", struct="Majority stake", seller="Hellenic Telecommunications Organization (OTE)"),
"EUR-122": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a",
                note="The sheet's GBP8m was Crane Electronics' ANNUAL SALES, not the consideration."),
"EUR-126": dict(val=8.9*1.28, loc="GBP 8.9m", disc="Disclosed"),
"EUR-127": dict(val=9.3, loc="~USD 9.3m all cash", disc="Disclosed", tier="Adjacent / Dual-Use", scope="Marginal"),
"EUR-128": dict(loc="Up to GBP 6.75m total consideration", basis="Maximum consideration", disc="Disclosed"),
"EUR-129": dict(stake="85%", struct="Majority stake", loc="~EUR 10.5m for 100%", disc="Disclosed"),
"EUR-130": dict(val=44.0*1.25, loc="GBP 44m cash (cash and debt free)", basis="Enterprise value", disc="Disclosed",
                ann="2024-05-01", note="Corrected from GBP6.9m / USD8.63m - an understatement of roughly 6.4x."),
"EUR-133": dict(tgt="Pressure Technologies PMC division (Al-Met, Roota Engineering, Martract)",
                val=6.2*1.28, loc="GBP 6.2m initial EV (up to GBP 7.7m)", basis="Initial enterprise value", disc="Disclosed",
                comp="2024-10-08", scope="Fail", dom="Oil & Gas Flow Control (non-A&D)",
                note="MERGED: EUR-133 and EUR-134 were the same single transaction, previously double-counted."),
"EUR-138": dict(val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a", ann="2024-10-22"),
"EUR-145": dict(loc="USD 6.4m (EUR 5.5m)", disc="Disclosed"),
"EUR-148": dict(stake="30% (alongside Grupo Oesia's 30%)", struct="Minority stake", val=None,
                loc="Not disclosed", disc="Not disclosed", basis="n/a", seller="Duro Felguera / SEPI"),
"EUR-149": dict(stake="55.33% (later 70.66%)", struct="Majority stake"),
"EUR-158": dict(struct="Asset purchase (Socializer Messenger product)", val=None, loc="3.5m VCI Global shares + right to acquire USD 1.5m of Treasure Global shares",
                disc="Not disclosed in cash terms", basis="n/a", scope="Fail", tier="Adjacent / Dual-Use",
                dom="Secure Messaging Software"),
"EUR-161": dict(stat="Announced/In Progress", comp=None, ann="2026-03-01", year=2026, stake="10% acquired to date; majority planned in tranches",
                struct="Staged minority stake", val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a",
                note="The sheet recorded a completed 100% acquisition on 25-Jun-2025 that had not occurred."),
"EUR-163": dict(stat="Announced/In Progress", comp=None, ann="2025-09-09", stake="29.9% by 31-Dec-2025; 70.1% by 31-Dec-2026",
                struct="Two-phase acquisition, subject to Golden Power clearance"),
"EUR-164": dict(ann="2025-07-19", comp="2025-07-19", val=None, loc="Not disclosed", disc="Not disclosed", basis="n/a"),
"EUR-191": dict(ac="Italy"),
"EUR-193": dict(struct="Pre-pack administration purchase", loc="GBP 280,000", disc="Disclosed"),
"EUR-196": dict(scope="Fail", tier="Adjacent / Dual-Use", dom="Investment Holding Company",
                note="Investment company (industry code 'Asset Management'); implied ~EUR205k market capitalisation is not a usable data point."),
"EUR-239": dict(tc="United Kingdom", hq="Sheffield, United Kingdom",
                note="DPC Holdings Limited is Jersey-incorporated; the operating business (Doncasters) is UK-based."),
"EUR-188": dict(scope="Fail", tier="Adjacent / Dual-Use", dom="Critical Metals Exploration",
                note="Ticker conflict in source data (target field 'LON: WFR' vs synopsis 'TAB'); pre-revenue tungsten explorer."),
"EUR-179": dict(scope="Fail", tier="Adjacent / Dual-Use", dom="Critical Metals Exploration"),
"EUR-183": dict(scope="Fail", dom="IT Consulting (non-A&D)"),
"EUR-005b": dict(),
}
# Rows removed from the Europe tab under the European-target-only rule (or as duplicates)
REMOVE = {
"EUR-108": "Target is Hexagon Masterworks Inc., a US entity (Salt Lake City). Only the seller, Hexagon Purus ASA, is Norwegian. Fails the European-target test.",
"EUR-100": "Fat Shark is a consumer FPV goggle brand divested by US-listed Red Cat Holdings; the UK target country is not supported. Fails the European-target test and the A&D test.",
"EUR-167": "Xer Technologies is Singapore-incorporated, and Rex International's staged minority investments in a related party are not a merger or acquisition. Fails both tests.",
"EUR-177": "The row is inverted: DCB Sports acquired the ESPORTS operations of Guild Esports plc for GBP100,000. The listed shell only renamed itself Defence Holdings in May-2025. No A&D company was acquired.",
"EUR-134": "Duplicate. Al-Met and Roota Engineering were a single transaction (Pressure Technologies PMC division) already recorded at EUR-133.",
}
